# Generated by Django 5.2.9 on 2025-12-20 22:46

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0003_compliancequery'),
    ]

    operations = [
        migrations.AddField(
            model_name='compliancequery',
            name='conversation_id',
            field=models.UUIDField(default=uuid.uuid4, help_text='Groups messages in a single chat session'),
        ),
    ]
