# Generated by Django 5.2.9 on 2025-12-21 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0005_globalnotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalnotification',
            name='action_draft',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='globalnotification',
            name='impact_level',
            field=models.CharField(default='LOW', max_length=20),
        ),
    ]
